#pragma once


typedef struct
{
	int number;
	int direction;

	int value_analog=0;
	int value_digital=0;

	int value_next=0;
	bool requestW;
	bool digitalW;
} PinData;


#include "Pin-autogenerated.h"