rem libraries
set makeheaders=..\non-uploaded-to-git\makeheaders.exe



%makeheaders% -h "multitasklib.cpp" > "multitasklib-autogenerated.h"

rem system

%makeheaders% -h "system/HAL/HAL.cpp" > "system/HAL/HAL-autogenerated.h"
%makeheaders% -h "system/Pin/Pin.cpp" > "system/Pin/Pin-autogenerated.h"
%makeheaders% -h "system/Main/Main.cpp" > "system/Main/Main-autogenerated.h"
%makeheaders% -h "system/MQTTManager/MQTTManager.cpp" > "system/MQTTManager/MQTTManager-autogenerated.h"
%makeheaders% -h "system/PrometheusHelper/PrometheusHelper.cpp" > "system/PrometheusHelper/PrometheusHelper-autogenerated.h"

rem tasks

%makeheaders% -h "Tasks\TaskCurrentMonitor\TaskCurrentMonitor.cpp" > "Tasks\TaskCurrentMonitor\TaskCurrentMonitor-autogenerated.h"
%makeheaders% -h "Tasks\TaskRelay\TaskRelay.cpp" > "Tasks\TaskRelay\TaskRelay-autogenerated.h"
%makeheaders% -h "Tasks\TaskFailureDetector\TaskFailureDetector.cpp" > "Tasks\TaskFailureDetector\TaskFailureDetector-autogenerated.h"
%makeheaders% -h "Tasks\TaskSafetyLock\TaskSafetyLock.cpp" > "Tasks\TaskTaskSafetyLock\TaskTaskSafetyLock-autogenerated.h"
%makeheaders% -h "Tasks\TaskTaskNetworkInterface\TaskTaskNetworkInterface.cpp" >  "Tasks\TaskTaskNetworkInterface\TaskTaskNetworkInterface-autogenerated.h"
%makeheaders% -h "Tasks\TaskPrometheus\TaskPrometheus.cpp" > "Tasks\TaskPrometheus\TaskPrometheus-autogenerated.h"
%makeheaders% -h "Tasks\Wifi\Wifi.cpp" > "Tasks\Wifi\wifi-autogenerated.h"



rem %makeheaders% -h "a_lib.cpp" >  "a_lib-autogenerated.h"
rem %makeheaders% -h "httprequestlib\httprequestlib.cpp" >  "httprequestlib\httprequestlib-autogenerated.h"
rem %makeheaders% -h another.cpp >> headers-autogenerated.h

rem or better, create a small tool that generates this script with the current file names
rem or better, use make