#pragma once

#include "../HAL/HAL.h"

#include "../../generalpurposelib.h"

HALdata machine;

char* metric1 =(char*) calloc(1,STRING_METRIC_SIZE);
char* metric2 =(char*) calloc(1,STRING_METRIC_SIZE);
//char metric1[200];


#define METRICS_SIZE 2 // TODO linked list?

#include "Main-autogenerated.h"
