#pragma once


#include <stdbool.h>

#include <Arduino.h>
#include <WiFi.h>
#include <iomanip>
#include <sstream>
#include <map>
#include <AsyncTCP.h>


uint32_t used_heap;
uint64_t last_push = 0;

AsyncClient* tcpClient = NULL;
String push_url;

#include "PrometheusHelper-autogenerated.h"
