#pragma once

#include <stdbool.h>

#include "../../multitasklib.h"

#include "../../Secrets/wifipsw.h"


#include "prometheusCfg.h"



typedef struct
{
	bool retry=0;
	DelayData timer;

} PrometheusTaskData;

PrometheusTaskData PrometheusRuntime;



#include "TaskPrometheus-autogenerated.h"